// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/catalogos": {
            "post": {
                "description": "Recebe os dados necessários para registrar um novo serviço no catálogo.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Catálogos"
                ],
                "summary": "Cadastra um novo catálogo",
                "parameters": [
                    {
                        "description": "Dados do Catálogo",
                        "name": "catalogo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CatalogoRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Catálogo criado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/response.CatalogoResponse"
                        }
                    },
                    "400": {
                        "description": "Dados inválidos (erro de validação do binding)",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Catálogo já cadastrado ou conflito de dados",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Falha na persistência de dados ou erro interno",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/catalogos/{id}": {
            "get": {
                "description": "Retorna os dados de um catálogo específico usando seu ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Catálogos"
                ],
                "summary": "Busca um catálogo pelo ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Catálogo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Catálogo encontrado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/response.CatalogoResponse"
                        }
                    },
                    "400": {
                        "description": "ID inválido fornecido",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Catálogo não encontrado",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor ou falha de infraestrutura",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/clientes": {
            "post": {
                "description": "Recebe dados de nome, email e telefone para registrar um novo cliente.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clientes"
                ],
                "summary": "Cadastra um novo cliente",
                "parameters": [
                    {
                        "description": "Dados do Cliente",
                        "name": "cliente",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.ClienteRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Cliente criado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/domain.Cliente"
                        }
                    },
                    "400": {
                        "description": "Dados inválidos (erro de validação do binding)",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Cliente já cadastrado (Email ou Telefone já existe)",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Falha na persistência de dados ou erro interno",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/clientes/{id}": {
            "get": {
                "description": "Retorna os dados de um cliente específico usando seu ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clientes"
                ],
                "summary": "Busca um cliente pelo ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Cliente",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cliente encontrado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/domain.Cliente"
                        }
                    },
                    "400": {
                        "description": "ID inválido fornecido (ex: formato incorreto se houver validação de formato de ID)",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Cliente não encontrado",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor ou falha de infraestrutura",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/prestadores": {
            "post": {
                "description": "Recebe os dados necessários para registrar um novo prestador.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Prestadores"
                ],
                "summary": "Cadastra um novo prestadores",
                "parameters": [
                    {
                        "description": "Dados do Prestador",
                        "name": "prestador",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.PrestadorRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Prestador criado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/response.PrestadorPostResponse"
                        }
                    },
                    "400": {
                        "description": "Dados inválidos (erro de validação do binding)",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Prestador já cadastrado ou conflito de dados",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Falha na persistência de dados ou erro interno",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/prestadores/{id}": {
            "get": {
                "description": "Retorna informações do prestador, incluindo catálogo de serviços e agenda diária.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Prestadores"
                ],
                "summary": "Consulta prestador pelo ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do prestador",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Prestador encontrado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/response.PrestadorResponse"
                        }
                    },
                    "404": {
                        "description": "Prestador não encontrado",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/prestadores/{id}/agenda": {
            "put": {
                "description": "Adiciona uma nova agenda diária à disponibilidade do prestador.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Prestadores"
                ],
                "summary": "Define a agenda diária de um prestador",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do prestador",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Agenda diária",
                        "name": "agenda",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AgendaDiariaRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Agenda adicionada com sucesso"
                    },
                    "400": {
                        "description": "Dados inválidos",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Prestador não encontrado",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflito de agenda",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Cliente": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "telefone": {
                    "type": "string"
                }
            }
        },
        "domain.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "request.AgendaDiariaRequest": {
            "type": "object",
            "required": [
                "data",
                "intervalos"
            ],
            "properties": {
                "data": {
                    "type": "string",
                    "example": "2025-01-03"
                },
                "intervalos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.IntervaloDiarioRequest"
                    }
                }
            }
        },
        "request.CatalogoRequest": {
            "type": "object",
            "required": [
                "categoria",
                "duracao_padrao",
                "nome",
                "preco"
            ],
            "properties": {
                "categoria": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3,
                    "example": "Redes"
                },
                "duracao_padrao": {
                    "type": "integer",
                    "example": 20
                },
                "nome": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3,
                    "example": "Tecnico de Redes"
                },
                "preco": {
                    "type": "number",
                    "example": 10000
                }
            }
        },
        "request.ClienteRequest": {
            "type": "object",
            "required": [
                "nome",
                "telefone"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "joao@email.com"
                },
                "nome": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3,
                    "example": "João da Silva"
                },
                "telefone": {
                    "type": "string",
                    "maxLength": 15,
                    "minLength": 8,
                    "example": "62999677481"
                }
            }
        },
        "request.IntervaloDiarioRequest": {
            "type": "object",
            "required": [
                "hora_fim",
                "hora_inicio"
            ],
            "properties": {
                "hora_fim": {
                    "type": "string",
                    "example": "12:00"
                },
                "hora_inicio": {
                    "type": "string",
                    "example": "08:00"
                }
            }
        },
        "request.PrestadorRequest": {
            "type": "object",
            "required": [
                "catalogo_ids",
                "nome",
                "telefone"
            ],
            "properties": {
                "catalogo_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "email": {
                    "type": "string",
                    "example": "joao@email.com"
                },
                "nome": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3,
                    "example": "joao"
                },
                "telefone": {
                    "type": "string",
                    "maxLength": 15,
                    "minLength": 8,
                    "example": "62999677481"
                }
            }
        },
        "response.AgendaDiariaResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                },
                "dia_semana": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "intervalos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.IntervaloDiarioResponse"
                    }
                }
            }
        },
        "response.CatalogoResponse": {
            "type": "object",
            "properties": {
                "categoria": {
                    "type": "string"
                },
                "duracao_padrao": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "preco": {
                    "type": "integer"
                }
            }
        },
        "response.IntervaloDiarioResponse": {
            "type": "object",
            "properties": {
                "hora_fim": {
                    "type": "string"
                },
                "hora_inicio": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "response.PrestadorPostResponse": {
            "type": "object",
            "properties": {
                "ativo": {
                    "type": "boolean"
                },
                "catalogo": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.CatalogoResponse"
                    }
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "telefone": {
                    "type": "string"
                }
            }
        },
        "response.PrestadorResponse": {
            "type": "object",
            "properties": {
                "agenda": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.AgendaDiariaResponse"
                    }
                },
                "ativo": {
                    "type": "boolean"
                },
                "catalogo": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.CatalogoResponse"
                    }
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "telefone": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "API de Agendamentos",
	Description:      "API para gestão de clientes e serviços.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
