// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/agendamentos": {
            "post": {
                "description": "Realiza o agendamento de um serviço para um prestador em uma data e horário específicos.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agendamentos"
                ],
                "summary": "Cria um novo agendamento",
                "parameters": [
                    {
                        "description": "Dados do agendamento",
                        "name": "agendamento",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request_agendamento.AgendamentoRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Agendamento criado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/response_agendamento.AgendamentoResponse"
                        }
                    },
                    "400": {
                        "description": "Dados inválidos ou formato de data incorreto",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Cliente, prestador ou serviço não encontrado",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflito de agenda (dia ou horário indisponível)",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/catalogos": {
            "get": {
                "description": "Retorna uma lista de catálogos, com page e limit para paginação",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Catalogo"
                ],
                "summary": "Lista todos os catálogos com paginação",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Número da página",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Quantidade de itens por página",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response_catalogo.CatalogoListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Cadastra um serviço que pode ser oferecido por um prestador",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Catálogos"
                ],
                "summary": "Cria um novo catálogo de serviços",
                "parameters": [
                    {
                        "description": "Dados do Catálogo",
                        "name": "catalogo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request_catalogo.CatalogoRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Catálogo criado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/response_catalogo.CatalogoResponse"
                        }
                    },
                    "400": {
                        "description": "Dados inválidos",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Prestador não encontrado",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Catálogo já existente",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/catalogos/{id}": {
            "get": {
                "description": "Retorna os dados de um catálogo específico usando seu ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Catálogos"
                ],
                "summary": "Busca um catálogo pelo ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Catálogo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Catálogo encontrado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/response_catalogo.CatalogoResponse"
                        }
                    },
                    "400": {
                        "description": "ID inválido fornecido",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Catálogo não encontrado",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor ou falha de infraestrutura",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/clientes": {
            "post": {
                "description": "Recebe dados de nome, email e telefone para registrar um novo cliente.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clientes"
                ],
                "summary": "Cadastra um novo cliente",
                "parameters": [
                    {
                        "description": "Dados do Cliente",
                        "name": "cliente",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.ClienteRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Cliente criado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/domain.Cliente"
                        }
                    },
                    "400": {
                        "description": "Dados inválidos (erro de validação do binding)",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Cliente já cadastrado (Email ou Telefone já existe)",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Falha na persistência de dados ou erro interno",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/clientes/{id}": {
            "get": {
                "description": "Retorna os dados de um cliente específico usando seu ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clientes"
                ],
                "summary": "Busca um cliente pelo ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Cliente",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cliente encontrado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/domain.Cliente"
                        }
                    },
                    "400": {
                        "description": "ID inválido fornecido (ex: formato incorreto se houver validação de formato de ID)",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Cliente não encontrado",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor ou falha de infraestrutura",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/prestadores": {
            "post": {
                "description": "Recebe os dados necessários para registrar um novo prestador.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Prestadores"
                ],
                "summary": "Cadastra um novo prestador",
                "parameters": [
                    {
                        "description": "Dados do Prestador",
                        "name": "prestador",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request_prestador.PrestadorRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Prestador criado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/response_prestador.PrestadorPostResponse"
                        }
                    },
                    "400": {
                        "description": "Dados inválidos (erro de validação do binding)",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Prestador já cadastrado ou conflito de dados",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Falha na persistência de dados ou erro interno",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/prestadores/{id}": {
            "get": {
                "description": "Retorna informações do prestador, incluindo catálogo de serviços e agenda diária.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Prestadores"
                ],
                "summary": "Consulta prestador pelo ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do prestador",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Prestador encontrado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/response_prestador.PrestadorResponse"
                        }
                    },
                    "404": {
                        "description": "Prestador não encontrado",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/prestadores/{id}/agenda": {
            "put": {
                "description": "Adiciona uma nova agenda diária à disponibilidade do prestador.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Prestadores"
                ],
                "summary": "Define a agenda diária de um prestador",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do prestador",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Agenda diária",
                        "name": "agenda",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request_prestador.AgendaDiariaRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Agenda adicionada com sucesso"
                    },
                    "400": {
                        "description": "Dados inválidos",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Prestador não encontrado",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflito de agenda",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Cliente": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "telefone": {
                    "type": "string"
                }
            }
        },
        "domain.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "domain.StatusDoAgendamento": {
            "type": "integer",
            "enum": [
                1,
                2,
                3,
                4
            ],
            "x-enum-varnames": [
                "Pendente",
                "Confirmado",
                "Cancelado",
                "Concluido"
            ]
        },
        "output.CatalogoOutput": {
            "type": "object",
            "properties": {
                "categoria": {
                    "type": "string"
                },
                "duracaoPadrao": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "imagemUrl": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "preco": {
                    "type": "integer"
                }
            }
        },
        "request.ClienteRequest": {
            "type": "object",
            "required": [
                "email",
                "nome",
                "telefone"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "joao@email.com"
                },
                "nome": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3,
                    "example": "João da Silva"
                },
                "telefone": {
                    "type": "string",
                    "maxLength": 15,
                    "minLength": 8,
                    "example": "62999677481"
                }
            }
        },
        "request_agendamento.AgendamentoRequest": {
            "type": "object",
            "required": [
                "catalogo_id",
                "cliente_id",
                "data_hora_inicio",
                "prestador_id"
            ],
            "properties": {
                "catalogo_id": {
                    "type": "string"
                },
                "cliente_id": {
                    "type": "string"
                },
                "data_hora_inicio": {
                    "type": "string",
                    "example": "2025-01-03T08:00:00Z"
                },
                "notas": {
                    "type": "string",
                    "maxLength": 500
                },
                "prestador_id": {
                    "type": "string"
                }
            }
        },
        "request_catalogo.CatalogoRequest": {
            "type": "object",
            "required": [
                "categoria",
                "duracao_padrao",
                "image_url",
                "nome",
                "preco"
            ],
            "properties": {
                "categoria": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3,
                    "example": "Redes"
                },
                "duracao_padrao": {
                    "type": "integer",
                    "example": 20
                },
                "image_url": {
                    "type": "string",
                    "example": "https://tdfuderuzpylkctxbysu.supabase.co/storage/v1/object/public/imagens/bb515383d2f6ef76.jpg"
                },
                "nome": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3,
                    "example": "Tecnico de Redes"
                },
                "preco": {
                    "type": "integer",
                    "example": 10000
                }
            }
        },
        "request_prestador.AgendaDiariaRequest": {
            "type": "object",
            "required": [
                "data",
                "intervalos"
            ],
            "properties": {
                "data": {
                    "type": "string",
                    "example": "2025-01-03"
                },
                "intervalos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request_prestador.IntervaloDiarioRequest"
                    }
                }
            }
        },
        "request_prestador.IntervaloDiarioRequest": {
            "type": "object",
            "required": [
                "hora_fim",
                "hora_inicio"
            ],
            "properties": {
                "hora_fim": {
                    "type": "string",
                    "example": "12:00"
                },
                "hora_inicio": {
                    "type": "string",
                    "example": "08:00"
                }
            }
        },
        "request_prestador.PrestadorRequest": {
            "type": "object",
            "required": [
                "catalogo_ids",
                "cpf",
                "nome",
                "telefone"
            ],
            "properties": {
                "catalogo_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "cpf": {
                    "type": "string",
                    "example": "04423258196"
                },
                "email": {
                    "type": "string",
                    "example": "joao@email.com"
                },
                "nome": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3,
                    "example": "joao"
                },
                "telefone": {
                    "type": "string",
                    "maxLength": 15,
                    "minLength": 8,
                    "example": "62999677481"
                }
            }
        },
        "response_agendamento.AgendamentoResponse": {
            "type": "object",
            "properties": {
                "data_fim": {
                    "type": "string"
                },
                "data_inicio": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "notas": {
                    "type": "string"
                },
                "prestador": {
                    "$ref": "#/definitions/response_agendamento.PrestadorInfo"
                },
                "servico": {
                    "$ref": "#/definitions/response_agendamento.ServicoInfo"
                },
                "status": {
                    "$ref": "#/definitions/domain.StatusDoAgendamento"
                }
            }
        },
        "response_agendamento.PrestadorInfo": {
            "type": "object",
            "properties": {
                "nome": {
                    "type": "string"
                },
                "telefone": {
                    "type": "string"
                }
            }
        },
        "response_agendamento.ServicoInfo": {
            "type": "object",
            "properties": {
                "duracao": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string"
                },
                "preco": {
                    "type": "integer"
                }
            }
        },
        "response_catalogo.CatalogoListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/output.CatalogoOutput"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "response_catalogo.CatalogoResponse": {
            "type": "object",
            "properties": {
                "categoria": {
                    "type": "string"
                },
                "duracao_padrao": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "preco": {
                    "type": "integer"
                }
            }
        },
        "response_prestador.AgendaDiariaResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "intervalos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response_prestador.IntervaloDiarioResponse"
                    }
                }
            }
        },
        "response_prestador.IntervaloDiarioResponse": {
            "type": "object",
            "properties": {
                "hora_fim": {
                    "type": "string"
                },
                "hora_inicio": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "response_prestador.PrestadorPostResponse": {
            "type": "object",
            "properties": {
                "ativo": {
                    "type": "boolean"
                },
                "catalogo": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response_catalogo.CatalogoResponse"
                    }
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "telefone": {
                    "type": "string"
                }
            }
        },
        "response_prestador.PrestadorResponse": {
            "type": "object",
            "properties": {
                "agenda": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response_prestador.AgendaDiariaResponse"
                    }
                },
                "ativo": {
                    "type": "boolean"
                },
                "catalogo": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response_catalogo.CatalogoResponse"
                    }
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "telefone": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "API de Agendamentos",
	Description:      "API para gestão de clientes e serviços.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
